export const VERTEX_LOCATIONS = [
  { id: 'global', name: 'global (auto-route)' },
  { id: 'us-central1', name: 'us-central1 (Iowa)' },
  { id: 'us-east1', name: 'us-east1 (South Carolina)' },
  { id: 'us-east4', name: 'us-east4 (Northern Virginia)' },
  { id: 'us-east5', name: 'us-east5 (Columbus, Ohio)' },
  { id: 'us-south1', name: 'us-south1 (Dallas, Texas)' },
  { id: 'us-west1', name: 'us-west1 (Oregon)' },
  { id: 'us-west4', name: 'us-west4 (Las Vegas, Nevada)' },
  { id: 'northamerica-northeast1', name: 'northamerica-northeast1 (Montreal)' },
  { id: 'southamerica-east1', name: 'southamerica-east1 (Sao Paulo)' },
  { id: 'europe-central2', name: 'europe-central2 (Warsaw)' },
  { id: 'europe-north1', name: 'europe-north1 (Finland)' },
  { id: 'europe-southwest1', name: 'europe-southwest1 (Madrid)' },
  { id: 'europe-west1', name: 'europe-west1 (Belgium)' },
  { id: 'europe-west2', name: 'europe-west2 (London)' },
  { id: 'europe-west3', name: 'europe-west3 (Frankfurt)' },
  { id: 'europe-west4', name: 'europe-west4 (Netherlands)' },
  { id: 'europe-west6', name: 'europe-west6 (Zurich)' },
  { id: 'europe-west8', name: 'europe-west8 (Milan)' },
  { id: 'europe-west9', name: 'europe-west9 (Paris)' },
  { id: 'asia-east1', name: 'asia-east1 (Taiwan)' },
  { id: 'asia-east2', name: 'asia-east2 (Hong Kong)' },
  { id: 'asia-northeast1', name: 'asia-northeast1 (Tokyo)' },
  { id: 'asia-northeast3', name: 'asia-northeast3 (Seoul)' },
  { id: 'asia-south1', name: 'asia-south1 (Mumbai)' },
  { id: 'asia-southeast1', name: 'asia-southeast1 (Singapore)' },
  { id: 'australia-southeast1', name: 'australia-southeast1 (Sydney)' },
  { id: 'me-central1', name: 'me-central1 (Doha)' },
  { id: 'me-central2', name: 'me-central2 (Dammam)' },
  { id: 'me-west1', name: 'me-west1 (Tel Aviv)' },
];
