// apps/desktop/src/renderer/components/settings/skills/mockSkills.ts

import type { Skill } from '@accomplish/shared';

export const MOCK_SKILLS: Skill[] = [
  {
    id: '1',
    name: 'skill-creator',
    command: '/skill-creator',
    description: 'Guide for creating effective skills. This skill should be used when users want to create a new custom skill.',
    source: 'official',
    isEnabled: true,
    isVerified: true,
    updatedAt: '2026-01-23',
  },
  {
    id: '2',
    name: 'code-review',
    command: '/code-review',
    description: 'Automated code review with best practices enforcement and security vulnerability detection.',
    source: 'official',
    isEnabled: true,
    isVerified: true,
    updatedAt: '2026-01-20',
  },
  {
    id: '3',
    name: 'similarweb-analytics',
    command: '/similarweb',
    description: 'Analyze websites and domains using SimilarWeb traffic data. Get traffic metrics and competitive insights.',
    source: 'official',
    isEnabled: false,
    isVerified: true,
    updatedAt: '2026-01-23',
  },
  {
    id: '4',
    name: 'git-commit',
    command: '/git-commit',
    description: 'Generate meaningful commit messages based on staged changes with conventional commit format support.',
    source: 'official',
    isEnabled: true,
    isVerified: false,
    updatedAt: '2026-01-18',
  },
  {
    id: '5',
    name: 'test-generator',
    command: '/test-gen',
    description: 'Automatically generate unit tests for your code with comprehensive coverage and edge cases.',
    source: 'official',
    isEnabled: false,
    isVerified: false,
    updatedAt: '2026-01-15',
  },
  {
    id: '6',
    name: 'doc-generator',
    command: '/doc-gen',
    description: 'Generate documentation from code comments, function signatures, and inline annotations.',
    source: 'official',
    isEnabled: false,
    isVerified: false,
    updatedAt: '2026-01-14',
  },
  {
    id: '7',
    name: 'api-designer',
    command: '/api-design',
    description: 'Design RESTful APIs with OpenAPI spec generation, endpoint planning, and schema validation.',
    source: 'community',
    isEnabled: false,
    isVerified: false,
    updatedAt: '2026-01-12',
  },
  {
    id: '8',
    name: 'sql-optimizer',
    command: '/sql-opt',
    description: 'Analyze and optimize SQL queries for better performance with index recommendations.',
    source: 'community',
    isEnabled: false,
    isVerified: false,
    updatedAt: '2026-01-10',
  },
  {
    id: '9',
    name: 'refactor-assist',
    command: '/refactor',
    description: 'Intelligent code refactoring suggestions with safe transformation patterns and previews.',
    source: 'community',
    isEnabled: false,
    isVerified: false,
    updatedAt: '2026-01-08',
  },
  {
    id: '10',
    name: 'debug-helper',
    command: '/debug',
    description: 'Analyze stack traces, suggest fixes for common errors, and help with debugging workflows.',
    source: 'community',
    isEnabled: false,
    isVerified: false,
    updatedAt: '2026-01-05',
  },
];
